version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    ports:
    - 9300:9300
    - 9200:9200
    environment:
      discovery.type: single-node
  node:
    image: node:10
    working_dir: /code
    volumes:
    - ./:/code
    network_mode: service:elasticsearch
